[rule]
description = """
Identifies calls to Windows memory APIs from unusual modules or NTDLL offsets. This may indicate an attempt to bypass
API monitoring using Return Oriented Programming (ROP) assembly gadgets to execute a syscall instruction.
"""
id = "2cb8bc8c-8eb7-418e-bb94-016460f8c6e1"
license = "Elastic License v2"
name = "VirtualProtect via Indirect Random Syscall"
os_list = ["windows"]
version = "1.0.6"

query = '''
api where 
 process.Ext.api.name : "VirtualProtect" and 
 not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: ("*NtProtectVirtualMemory*", "*ZwProtectVirtualMemory*")) and 
 process.thread.Ext.call_stack_final_user_module.name != null and process.executable != null and 
  (
   process.thread.Ext.call_stack_summary : "ntdll.dll|Unbacked" or 
   endswith~(process.executable, process.thread.Ext.call_stack_final_user_module.name) or 
   endswith~(process.executable, process.thread.Ext.call_stack_final_user_module.protection_provenance) or 
   (process.thread.Ext.call_stack_final_user_module.name : "Unbacked" and process.thread.Ext.call_stack_final_user_module.protection_provenance : "Unbacked")
   ) and 
  _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: "?:\\windows\\system32\\ntdll.dll!*+0x14") and 
 not process.thread.Ext.call_stack_final_user_module.protection_provenance : "kernel" and 
 not process.thread.Ext.call_stack_final_user_module.name : "kernel" and 
 not process.thread.Ext.call_stack_summary : "Unbacked|Unknown|umppc*.dll|ntdll.dll"
'''

min_endpoint_version = "8.10.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1036"
name = "Masquerading"
reference = "https://attack.mitre.org/techniques/T1036/"

[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
