[rule]
description = """
Identifies instances where a dynamic library (dylib) is loaded from a volume mount path on macOS. Threat actors may
abuse this technique to load malicious dylibs from external or mounted volumes, which can be used to perform code
injection, persistence, or privilege escalation. By loading a dylib from a volume mount path, attackers can bypass
certain security mechanisms and avoid raising suspicion as the malicious code is not stored within the application
bundle or the system's default library locations.
"""
id = "d92e00d3-d6a4-4662-b585-c666d05d2e9a"
license = "Elastic License v2"
name = "Suspicious Dylib Load from Volume Mount Path"
os_list = ["macos"]
version = "1.0.17"

query = '''
any where (
            (event.action == "load" and dll.path : "/Volumes/*" and (process.code_signature.exists == false or process.code_signature.trusted == false) and 
              not process.executable : ("/Volumes/*", 
                                        "/Users/*/.nvm/*", 
                                        "/Users/*/.rustup/toolchains/stable-aarch64-apple-darwin/*")) or 
            (event.action == "load" and process.executable : "/Volumes/*" and (dll.code_signature.exists == false or dll.code_signature.trusted == false) and 
              not dll.path : ("/Volumes/*", 
                              "/System/Library/*", 
                              "/usr/lib/*", 
                              "/private/var/db/oah/*") and
              not process.code_signature.team_id : "QGULMAPEB2")
          )
'''

min_endpoint_version = "8.7.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1574"
name = "Hijack Execution Flow"
reference = "https://attack.mitre.org/techniques/T1574/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.7.0"
