[rule]
description = """
Identifies suspicious Windows memory APIs called from a Microsoft Office application. Adversaries may attempt to gain
initial access via malicious macro documents implementing code injection to evade defenses.
"""
id = "a28a13c6-0446-4ed4-828b-63bd3b177ff4"
license = "Elastic License v2"
name = "Suspicious API Call from a Microsoft Office Document"
os_list = ["windows"]
reference = ["https://attack.mitre.org/techniques/T1055/"]
version = "1.0.8"

query = '''
api where
 process.name : ("WINWORD.EXE", "EXCEL.EXE", "MSPUB.EXE", "fltldr.exe") and
 (
  process.Ext.api.name : "VirtualProtectEx" or
  (process.Ext.api.name : "VirtualAlloc*" and process.Ext.api.parameters.protection : "*X*" and
   process.Ext.api.parameters.size >= 4000) or
  (process.Ext.api.name : "WriteProcessMemory" and process.Ext.api.parameters.size >= 4000) or
  process.Ext.api.behaviors : ("shellcode", "allocate_shellcode", "execute_shellcode") or 
  (process.Ext.api.name : "VirtualProtect" and process.Ext.api.metadata.target_address_name : "Unbacked" and 
   process.Ext.api.parameters.protection : "RWX" and process.Ext.api.parameters.size >= 4000)
 ) and
  process.thread.Ext.call_stack_final_user_module.name : "vbe?.dll" and
  not _arraysearch(process.thread.Ext.call_stack, $entry,
                     $entry.protection_provenance : ("fships.dll*", "Kernel*", "mfehcthe.dll", "mfehcs.exe|mfehcs.exe", "keylib64.dll",
                                                     "keylib32.dll", "psnmvtools64.dll", "psnmvtools64.dll|psnmvinj.dll", "epmpthe.dll",
                                                     "f_nx.dll")) and
  not _arraysearch(process.thread.Ext.call_stack, $entry,
                   $entry.symbol_info: ("?:\\windows\\sys*\\driverstore\\filerepository\\*",
                                        "?:\\windows\\sys*\\d3d11.dll!CreateDirect3D*",
                                        "?:\\program files*\\sentinelone\\*",
                                        "*ntdll.dll!NtCreateUserProcess*",
                                        "*kernelbase.dll!CreateProcess*")) and
  not process.thread.Ext.call_stack_summary : ("unbacked", "unknown") and 
  not process.Ext.api.summary : "VirtualAlloc*IMAGE_RANGE,*"
'''

min_endpoint_version = "8.10.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1566"
name = "Phishing"
reference = "https://attack.mitre.org/techniques/T1566/"
[[threat.technique.subtechnique]]
id = "T1566.001"
name = "Spearphishing Attachment"
reference = "https://attack.mitre.org/techniques/T1566/001/"

[[threat.technique.subtechnique]]
id = "T1566.002"
name = "Spearphishing Link"
reference = "https://attack.mitre.org/techniques/T1566/002/"



[threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
